# Copyright 2020, Oracle Corporation and/or affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl
# MAINTAINER <paramdeep.saini@oracle.com>
#
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "oracle-si-shards.fullname" . }}
  labels:
{{ include "oracle-si-shards.labels" . | indent 4 }}
spec:
  storageClassName: "{{ .Values.pvc.storageClassName }}"
  accessModes:
  - "{{ .Values.pvc.accessModes }}"
  resources:
    requests:
      storage: {{ .Values.pvc.storageSize }}
