## Copyright 2020, Oracle Corporation and/or affiliates.  All rights reserved.
### Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl
### MAINTAINER <paramdeep.saini@oracle.com>
---
# tasks file for oci-build-gsm-docker-image

- name: Extract GSM zipped dockerfiles on remote machine under "{{ gsm_dockerfiles_remote_loc }}"
  unarchive:
    src: "{{ gsm_dockerfiles_source_file }}"
    dest: "{{ gsm_dockerfiles_remote_loc }}"

- name: copying GSM software zipped file to remote machine to build the docker image 
  copy: 
    src="{{ gsm_software_source_file }}"
    dest="{{ gsm_software_remote_file }}"

- name: Build the docker image on remote machine
  command: "{{ gsm_dockerfiles_remote_loc }}/oracle-gds-docker-image/dockerfiles/buildDockerImage.sh -v {{ gsm_software_version }}"
