## Copyright 2020, Oracle Corporation and/or affiliates.  All rights reserved.
## Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl
## MAINTAINER <paramdeep.saini@oracle.com>
---
 - name: Setting up network subnets for OKE cluster
   hosts: localhost
   vars_files:
     - samples/oci-oke-setup-env.yaml
   roles:
      - oci-setup-oke-network

 - name: Setting up OKE cluster 
   hosts: localhost
   vars_files:
     - samples/oci-oke-setup-env.yaml
   roles:
     - oci-launch-oke-cluster

#- name: Building GSM image and uploading to OCIR
#   hosts: 129.146.56.87   
#   become: yes
#   remote_user: opc
#   vars_files:
#     - samples/oci-oke-setup-env.yaml
#   roles:
#     - oci-build-gsm-docker-image
#     - oci-upload-gsm-image-ocir
