version: '3.7'
services:
  web:
    image: oracle/oracle-sdb-mid-tier-routing-services:latest
    environment:
      - CATALOG_URL=jdbc:oracle:thin:@<host>:<port>:<service>
      - CATALOG_USERNAME=app_schema
      - CATALOG_PASSWD=app_schema
      - CATALOG_SVC_NAME=<service_name>
      - SWIM_LANE_CACHE_HOST=localhost
      - SWIM_LANE_CACHE_PORT=0
      - SWIM_LANE_CACHE_TYPE=IN_MEM_CACHE
    ports:
      - "8080:8080"
