## Copyright 2020, Oracle Corporation and/or affiliates.  All rights reserved.
### Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl
### MAINTAINER <paramdeep.saini@oracle.com>
quad_zero_route: "0.0.0.0/0"
TCP_protocol: "6"
SSH_port: "22"
vcn_name: "okevcn"
vcn_cidr_block: "10.0.0.0/16"
vcn_dns_label: "okevcn"
ig_name: "internetgatewayformyokevcn"
route_table_name: "okeroutetable"
route_table_rules:
   - cidr_block: "{{ quad_zero_route }}"
     network_entity_id: "{{ ig_id }}"
subnet_cidr: "10.0.0.48/28"
subnet_dns_label: "okesubnet"
subnet1_cidr: "10.0.0.0/24"
subnet2_cidr: "10.0.1.0/24"
subnet3_cidr: "10.0.2.0/24"
subnet1_name: "okesubnet1"
subnet2_name: "okesubnet2"
subnet3_name: "okesubnet3"
lb_subnet1_cidr: "10.0.20.0/24"
lb_subnet2_cidr: "10.0.21.0/24"
lb_subnet1_name: "LB Subnet1"
lb_subnet2_name: "LB Subnet2"
cluster_name: "oke_cluster"
oracle_gsm_pool_name: "oracle_gsm_node_pool"
oracle_shards_pool_name: "oracle_shards_node_pool"
node_image_name: "Oracle-Linux-7.4"
node_shape: "VM.Standard2.4"
OKE_ip_address1: "130.35.0.0/16"
OKE_ip_address2: "134.70.0.0/17"
OKE_ip_address3: "138.1.0.0/16"
OKE_ip_address4: "140.91.0.0/17"
OKE_ip_address5: "147.154.0.0/16"
OKE_ip_address6: "192.29.0.0/16"
ad1: "{{ lookup('env', 'SAMPLE_AD1_NAME') }}"
ad2: "{{ lookup('env', 'SAMPLE_AD2_NAME') }}"
ad3: "{{ lookup('env', 'SAMPLE_AD3_NAME') }}"
cluster_compartment: "{{ lookup('env', 'SAMPLE_COMPARTMENT_OCID') }}"
kubeconfig_path: "{{ lookup('env', 'KUBECONFIG_PATH') }}"
oke_cluster_ssh_public_key: "<<ENTER YOU PUBLIC KEY HERE>>"
#################### Section 2 - Build Docker GSM Image ########################
gsm_software_version: "19.3.0"
gsm_dockerfiles_source_file: "/tmp/gsm_dockerfiles.zip"
gsm_dockerfiles_remote_loc: "/tmp"
gsm_software_source_file: "/scratch/psaini/oracle/software/LINUX.X64_193000_gsm.zip"
gsm_software_remote_file: "{{ gsm_dockerfiles_remote_loc }}/oracle-gds-docker-image/dockerfiles/{{ gsm_software_version }}/LINUX.X64_193000_gsm.zip"
